ui = fluidPage(
      fluidRow(
        column(width = 3,
               shiny::br(),
         sliderInput("sigma2",
                     HTML("<h3>Noise Value (&sigma;):</h3>"),
                     min = 0.05,
                     max = 5,
                     value = 0.25,
                     step = 0.05,
                     animate = animationOptions(interval = 250, loop = F)),
         sliderInput("degree",
                     HTML("<h3>Polynomial Degree</h3>"),
                     min = 1,
                     max = 12,
                     value = 2,
                     step = 1,
                     animate = animationOptions(interval = 250, loop = F))
         # shiny::br(),
         # shiny::hr(),
         # shiny::br(),
         # uiOutput("sumd"),
         # shiny::br(),
         # shiny::hr(),
         # shiny::br(),
         # uiOutput("sumda"),
         # shiny::br(),
         # shiny::hr(),
         # shiny::br(),
         # uiOutput("sumd2")
         ),
                column(width = 9,
      mainPanel(width = "100%",
         plotOutput("plot3d2", height = "550px")))))
