ui = fluidPage(
      fluidRow(
        column(width = 3,
               shiny::br(),
         sliderInput("sigma",
                     HTML("<h3>Noise Value (&sigma;):</h3>"),
                     min = 0.05,
                     max = 5,
                     value = 0.25,
                     step = 0.05,
                     animate = animationOptions(interval = 250, loop = F)),
         selectInput("showline",
                     HTML("<h3>Show Fit Line</h3>"),
                     choices = c("Yes", "No"),
                     selected = "Yes"),
         shiny::br(),
         shiny::hr(),
         shiny::br(),
         uiOutput("sumd"),
         shiny::br(),
         shiny::hr(),
         shiny::br(),
         uiOutput("sumda"),
         shiny::br(),
         shiny::hr(),
         shiny::br(),
         uiOutput("sumd2")),
                column(width = 9,
      mainPanel(width = "100%",
         plotOutput("plot3d", height = "550px")))))
